services:
  film-checker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      - DB_PATH=/data/films.db
      - SERVICE_FQDN_FILM_CHECKER=films.alaloupe.fr
    volumes:
      - film-checker-data:/data
    restart: unless-stopped

volumes:
  film-checker-data:
